### ISSUE TITLE
Thunderbird Daily Download links for l10n packages seems not working

### ISSUE THREAD

**Issue by monstorix** [thunderbird/thunderbird-website#686] opened 2024-11-02 08:33 UTC
The Thunderbird download page now uses this link to get the local language version of package (Simplified Chinese as example):
```https://download.mozilla.org/?product=thunderbird-nightly-latest-SSL&os=linux64&lang=zh-CN``` 
But atm this link only redirect to the English package.

After adding the same parameters as Firefox Nightly in the URL, I can download Thunderbird Daily in my local language:
```https://download.mozilla.org/?product=thunderbird-nightly-latest-l10n-SSL&os=linux64&lang=zh-CN```

~~Maybe some parameters has been missing in the new website?~~

**Comment by Sancus** [comment] 2024-11-02 19:08
I cannot reproduce any issue with these URLs. What language are you actually trying to download?

https://download.mozilla.org/?product=thunderbird-128.4.0esr-SSL&os=linux64&lang=fr
https://download.mozilla.org/?product=thunderbird-128.4.0esr-SSL&os=linux64&lang=de

both download the French and German versions respectively without any problem.

**Comment by monstorix** [comment] 2024-11-03 02:06
@Sancus Sorry, I found that the problem is only in the Daily download links, not ESR/Release download links.

I tried with Chinese and Japanese under Linux. The original Daily links just download the packages with English language pack preloaded until I add the parameters (latest-l10n-ssl) into links.

I'll change the issue title.

**Comment by MelissaAutumn** [comment] 2024-11-03 16:36
Seems to be a link bouncer issue unless I'm forming the links wrong.

Ex/
https://download.mozilla.org/?product=thunderbird-nightly-latest-SSL&os=linux64&lang=ja

**Comment by Sancus** [comment] 2024-11-03 17:51
Yes, I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1928853

**Comment by Sancus** [comment] 2024-11-04 20:17
https://download.mozilla.org/?product=thunderbird-nightly-latest-l10n-SSL&os=win64&lang=en-US works just fine so I think we can just use that one pattern for all links, just add `-l10n` in to the existing ones.

**Comment by MelissaAutumn** [comment] 2024-11-04 21:35
I've pushed a fix on stage, will verify it's all working correctly and push up on prod tomorrow.

**Comment by MelissaAutumn** [comment] 2024-11-05 16:24
Looks good I've push this up to prod. Should be fixed in a few hours once caching runs out.

**Closed by MelissaAutumn** 2024-11-05 16:24 UTC
