### ISSUE TITLE
Holiday Calendars are broken

### ISSUE THREAD

**Issue by byquanton** [thunderbird/thunderbird-website#645] opened 2024-09-14 11:19 UTC
Clicking on a calendar on https://www.thunderbird.net/en-US/calendar/holidays/ results in an endless redirect.

**Comment by MelissaAutumn** [comment] 2024-09-14 15:28
Thanks for the report!

Caused by https://github.com/thunderbird/thundernest-ansible/blob/25200c788ea5b3576a8d41aad3052d3659e50188/vars/apache.yml#L191

Will look into it next week.

**Comment by Sancus** [comment] 2024-09-20 19:31
Thanks for the fix, merged and deployed and testing shows it's working now.

Mind that browsers are very aggressive with caching redirects so if you test and it appears still broken, try in a private tab or rarely used browser.

**Closed by Sancus** 2024-09-20 19:31 UTC
Labels: bug
